### ISSUE TITLE
Support Batched Transactions for File Create Transaction and File Append Transaction

### ISSUE THREAD

**Issue by QuestofIranon** [hashgraph/hedera-improvement-proposal#10]
## Simple Summary
Allow batched file uploads using File Create and File Append transactions.

## Abstract
Currently all file uploads are required to be serial File Create => File Append => ... => File Append transactions. This requires each transaction to wait for a receipt before performing the next append or else byte order is lost and the file becomes corrupt. I propose introducing a method to send multiple append transactions simultaneously with the original byte order preserved. This will allow for batch append transactions and speed up the process of uploading a file.

## Motivation
Allow for faster file upload times and easier cost estimation for file uploads. Currently a 1 megabyte file is required to be split into roughly 2-300 transactions. Running against the testnet, each append cycle takes roughly 1 second to send the transaction and wait for a receipt. Any file of significant size could potentially take multiple hours to upload increasing the risk of failure or user losing interest. Price could also fluctuate, resulting in poor cost estimation and a displeased user when they realize their file failed to upload due to insufficient balance or their balance was much lower than initially anticipated.

## Specification
I leave this up to the community and/or developers to determine. My naive solution would be to have the initial file create transaction include fields for total byte and block/chunk size and each append transaction would contain the position. A file info transaction or the receipt could provide details regarding missing or incomplete blocks for fault tolerance. This would allow a file to be chunked by the user and all transactions sent immediately, then the returned receipts can be checked to determine percentage completed and which blocks should be retried.

## Backwards Compatibility
Serial upload via append file could continue to be supported in cases where a file size and block size are not included.

## Scope and impact
Properties I am aware of:
Internal hashgraph implementation
My Hbar Wallet
Hedera Javascript SDK
Hedera Java SDK
Hedera-CLI

Does it require Hedera support, or potential funding? Let the community know.
It requires Hedera's developers to implement the feature

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by Cooper-Kunz** [comment]
Hey @QuestofIranon - thank you for your suggestion and proposal!

We're still finalizing the HIP process + example template (#9) but once that is in place, would you be able to resubmit via the pull request process that will be outlined there? Then we can discuss feasibility, interest/support from the community, implementation details, etc. 👍

**Comment by publu** [comment]
+ scope for Composer chrome extension. It features file get/setters

**Comment by QuestofIranon** [comment]
@Cooper-Kunz will do. I used the template that seemed to exist right now. Is there an eta on when I should check (or can you ping me again)?

**Comment by Cooper-Kunz** [comment]
Yes, I can certainly ping you @QuestofIranon! For clarity, you followed the correct template! But once this process has been approved, HIPs will need to be checked in files rather than issues 👍

**Comment by donaldthibeau** [comment]
Discussed internally with Hedera development team. Current thinking is that this will not currently be prioritized by our team. The reasoning is as follows:
- Hedera is not optimized for large file storage. The use cases targeted are more for file pointers, credentials, and other smaller files.
- Would require more substantial changes to HAPI.

As such, I will leave this open in the backlog in case there is additional community interest, or another community member would like to pick this up, similar to Composer.

**Comment by kenthejr** [comment]
@QuestofIranon if you'd like to submit this as a HIP, please do so. We love these kinds of contributions. If no action is taken I'll close this thread out in 7 days.
