### ISSUE TITLE
HRC category could apply to core, interface, or economics

### ISSUE THREAD

**Issue by paulmadsenhed** [hashgraph/hedera-improvement-proposal#11]
The categories suggest a HIP would be either core, interface, economics OR HRC. 

But if HRC is a HIP that implies obtaining feedback from the Hedera team, then that would seem to apply to many HIPs that would fit into core, interface or economics

**Comment by paulmadsenhed** [comment]
perhaps HRC is a separate flag?

**Comment by Cooper-Kunz** [comment]
This would make sense to myself @paulmadsenhed - thanks for your thoughts.

For clarity, I understand this as a request to update the README and the example template. 

Is there anything else that this would potentially impact?

**Comment by paulmadsenhed** [comment]
yes

**Comment by Cooper-Kunz** [comment]
Hey @paulmadsenhed are you okay with the changes made in f7b01d418ef32398ad97e2d9cf22d577c5c68c5b? 

If so, feel free to close. Otherwise, let me know how else we can make it more clear.

**Comment by paulmadsenhed** [comment]
works for me
