### ISSUE TITLE
Document HAPI Feature Matrix in SDKs

### ISSUE THREAD

**Issue by donaldthibeau** [hashgraph/hedera-improvement-proposal#14]

**Comment by kenthejr** [comment]
https://docs.google.com/spreadsheets/d/1GuQF8aiBf4Cb832jbRkHWlrO9xlmA_ZSyO78_7X1EMs/edit?usp=sharing

**Comment by publu** [comment]
What does the * mean?

**Comment by donaldthibeau** [comment]
What is next step here? Do we need to add to docs.hedera.com, or can we close out this HIP?

**Comment by donaldthibeau** [comment]
Can I close this @kenthejr ?
