### ISSUE TITLE
Hedera SDK - Swift

### ISSUE THREAD

**Issue by atul-hedera** [hashgraph/hedera-improvement-proposal#19]
Lower priority - take it up after Java SDK for HCS, Go SDK, and completion of Javascript SDK

**Comment by Cooper-Kunz** [comment]
Hey @atul-hedera or @kenthejr are you able to resubmit with the [example template](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/0000-template.md)?

**Comment by craigdrabiktxmq** [comment]
I'm in conversations with some community members about this topic.  I'm happy to start a formal HIP as soon as I can free up enough time to do so (or contribute to one someone else starts).

I can tell you there is interest in the community, and not just from iOS developers but from those of us who are doing hybrid mobile development as well.

**Comment by kenthejr** [comment]
No HIP submitted
