### ISSUE TITLE
Hedera Ledger Protocol

### ISSUE THREAD

**Issue by publu** [hashgraph/hedera-improvement-proposal#28]
# Improvement Description
 * One-line improvement description: Define Hashgraph Ledger Protocol for tokenization. I recommend using [Bitcoin Cash's Simple Ledger Protocol](https://github.com/simpleledger/slp-specifications/blob/master/slp-token-type-1.md) as the base. 
 * Hedera Improvement Proposal: TBD
 * Primary Contact (assignee): @itspublu

**Comment by donaldthibeau** [comment]
Please tag me once the HIP is complete for review.

**Comment by publu** [comment]
Here's an initial document outlining the specifications:
https://docs.google.com/document/d/1fV0rDRL4kstfRoOQdWAdP4kG6pllXrcvKVTQEFRD6Cc/edit

**Comment by kenthejr** [comment]
We love your input. The HIP process has been updated and we look forward to your contribution. If you still would like to pursue this as an improvement, please submit a Hedera Improvement Proposal in accordance with [hip-1](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-1.md). If no further action is taken within 7 days, this issue will be closed.
