### ISSUE TITLE
Smart Contract use block.difficulty to return nano seconds part of transaction consensus time

### ISSUE THREAD

**Issue by czemelman** [hashgraph/hedera-improvement-proposal#29]
Currently block.timestamp is returning  consensus time in seconds trimming the nanoseconds part out.
Fr some smart contracts it may be beneficial to know  the exact consensus time epoch seconds + nano seconds.  I suggest to utilize block.difficulty that is currently not in use to return consensus time nano seconds.

**Comment by donaldthibeau** [comment]
This is currently in the backlog and not yet prioritized for a release.

**Comment by donaldthibeau** [comment]
@tinker-michaelj please open a bug in services.

**Comment by kenthejr** [comment]
Per @donaldthibeau comment, this is addressed internally.
