### ISSUE TITLE
Integrating smart contracts with consensus service

### ISSUE THREAD

**Issue by publu** [hashgraph/hedera-improvement-proposal#30]
One-line improvement description: Integrate smartContractCallLocal as an access control mechanism for submitting messages to an HCS topic.
Primary Contact (assignee): @publu

**Comment by kenthejr** [comment]
We love your input. If you still would like to pursue this as an improvement, please submit a Hedera Improvement Proposal in accordance with [hip-1](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-1.md). If no further action is taken within 7 days, this issue will be closed.
