### ISSUE TITLE
Integrate crypto payments to HCS topics

### ISSUE THREAD

**Issue by publu** [hashgraph/hedera-improvement-proposal#31]
I think it would be very useful if we could have HCS topics carrying payments so that we can enable atomic swaps over tokens

**Comment by Ra1den54** [comment]
I think this is a great idea.

**Comment by kenthejr** [comment]
This is very interesting. I would love to see it fleshed out. If you still would like to pursue this as an improvement, please submit a Hedera Improvement Proposal in accordance with [hip-1](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-1.md). If no further action is taken within 7 days, this issue will be closed.
