### ISSUE TITLE
Fungible Token Service transfers on HCS topics

### ISSUE THREAD

**Issue by christianholman** [hashgraph/hedera-improvement-proposal#33]
This builds off of #31. Allowing for fungible token service transfers with HCS messages would allow for even greater interoperability.

**Comment by kenthejr** [comment]
We love your input. If you still would like to pursue this as an improvement, please submit a Hedera Improvement Proposal in accordance with [hip-1](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-1.md). If no further action is taken within 7 days, this issue will be closed.
