### ISSUE TITLE
Optional Hedera address check-sums to prevent manual data entry mistakes

### ISSUE THREAD

**Issue by zoperado** [hashgraph/hedera-improvement-proposal#34]
The Hedera Hashgraph address format 0.0.12345 is a compact address identifier that has the advantage of being easy to memorize and communicate. However, it is prone to manual data entry mistakes as it's likely to leave a digit out, permute, or accidentally add extra digits to an address. When the wrong address is put in the recipient field of a Hedera wallet then funds are transferred out irreversibly. 

Furthermore, a malicious actor could reserve addresses that are similar to ones of high value and high traffic accounts, such as accounts of exchanges, in order to take advantage of such addressing mistakes. Also, due to low account creation fees, a malicious actor can reserve a whole block of addresses , several thousand in a couple of hours, to maximize the probability of funds being transferred by mistake to one of the malicious accounts . 

To prevent such manual entry mistakes, we propose the introduction of address check-sums, which could be optional to preserve address backward compatibility.

**Comment by lbaird** [comment]
A proposal to address this is #35

**Comment by kenthejr** [comment]
Excellent idea. Being addressed in #35
