### ISSUE TITLE
Return decimal property with token balances

### ISSUE THREAD

**Issue by kenthejr** [hashgraph/hedera-improvement-proposal#36]
---

hip: 0000-token-decimals-with-balance
title: Return decimal property with token balances
authors: Ken Anderson (@kenthejr)
type: Standards Track
category: Interface
created: 2021-01-15
status: Draft

---

## Summary
The Hedera API (HAPI) should return the token decimal property with all token balance results.

## Motivation
Token balances are difficult or impossible to parse without knowing the decimal property of the token definition. For example, "100000" with 2 decimal places (1,000.00) is very different from 4 decimal places (10.0000).

In order for an application to make sense of responses that contain token balances, the application must make an additional query to HAPI to retrieve the token info. This can be cumbersome and relatively costly for accounts that hold multiple tokens or when querying many accounts holding many tokens.

One approach would be for the application to cache token info, but token info can be updated.

Fundamentally, a decentralized client application should have sufficient information from a `CryptoGetInfo` (via the `TokenRelationship` message) or `CryptoGetBalance` query to present the user with an accurate representation of token balances.

## Goals

* Enable client applications to present token balances meaningfully without dependencies on third-party services, follow-up queries, or caches.

## Specification

Update https://github.com/hashgraph/hedera-protobuf/blob/master/src/main/proto/CryptoGetAccountBalance.proto:

```
message TokenBalance {
    TokenID tokenId = 1; // The ID of the token
    uint64 balance = 2; // The current token balance
}
```
to become
```
message TokenBalance {
    TokenID tokenId = 1; // The ID of the token
    uint64 balance = 2; // The current token balance
    uint32 decimals = 3; // The decimal property of the token
}
```

Update https://github.com/hashgraph/hedera-protobuf/blob/master/src/main/proto/CryptoGetInfo.proto:

```
message TokenRelationship {
    TokenID tokenId = 1; // The ID of the token
    string symbol = 2; // The Symbol of the token
    uint64 balance = 3; // The balance that the Account holds in the smallest denomination
    TokenKycStatus kycStatus = 4; // The KYC status of the account (KycNotApplicable, Granted or Revoked). If the token does not have KYC key, KycNotApplicable is returned
    TokenFreezeStatus freezeStatus = 5; // The Freeze status of the account (FreezeNotApplicable, Frozen or Unfrozen). If the token does not have Freeze key, FreezeNotApplicable is returned
}
```
to become
```
message TokenRelationship {
    TokenID tokenId = 1; // The ID of the token
    string symbol = 2; // The Symbol of the token
    uint64 balance = 3; // The balance that the Account holds in the smallest denomination
    TokenKycStatus kycStatus = 4; // The KYC status of the account (KycNotApplicable, Granted or Revoked). If the token does not have KYC key, KycNotApplicable is returned
    TokenFreezeStatus freezeStatus = 5; // The Freeze status of the account (FreezeNotApplicable, Frozen or Unfrozen). If the token does not have Freeze key, FreezeNotApplicable is returned
    uint32 decimals = 6; // The decimal property of the token
}
```

## Backwards Compatibility
This should not introduce any incompatibilities

## Scope and Impact

* HAPI Protobufs: should be updated per the above recommendation
* SDKs: should be updated to relay the updated decimals property

**Comment by kenthejr** [comment]
I will resubmit as a HIP.

**Comment by tinker-michaelj** [comment]
Is in `v0.12.0`, closed by https://github.com/hashgraph/hedera-services/issues/1075
