### ISSUE TITLE
NFT Metadata JSON

### ISSUE THREAD

**Issue by sam-at-luther** [hashgraph/hedera-improvement-proposal#40]
A key accelerator to the adoption of the ERC721 [0] Non Fungible Tokens (NFT) standard for the Ethereum network is the "ERC721 Metadata JSON Schema" definition. This schema is part of the optional metadata extension of that standard, and provides a guidelines for the format of the data that served for a token's metadata URI. This standard is how the plethora of wallets in that ecosystem (for example OpenSea [1] and d'cent [2]) display asset attributes for many ERC721 implementations, including an image for each NFT. 

Building on the success of that standard, I propose _optionally_ adopting this same JSON schema standard for NFT metadata on HTS. Specifically,

```
{
    "title": "Asset Metadata",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "Identifies the asset to which this NFT represents"
        },
        "description": {
            "type": "string",
            "description": "Describes the asset to which this NFT represents"
        },
        "image": {
            "type": "string",
            "description": "A URI pointing to a resource with mime type image/* representing the asset to which this NFT represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive."
        }
    }
}
```

I also would like to solicit feedback on how the community thinks is best to include URIs that serve metadata in the above format within HTS NFTs. 

Based on these discussions, I'm eager to draft a HIP and be a champion for such a standard.

[0] https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md#specification
[1] https://opensea.io/
[2] https://dcentwallet.com/

**Comment by rahul-kothari** [comment]
for images/videos - probably use IPFS to ensure authenticity? Pinata is also another interesting idea!

**Comment by cylon56** [comment]
Here is a potential add-on to this proposal or a separate HIP for NFTs. **HTS should support the creation of numerous non-fungible tokens of a single type**. 

Currently, it seems that NFTs can only work on HTS if you create a token with a supply of one and treat it as an NFT. This seems like a workaround for now and leaves a lot to be desired. In addition to having embedded metadata, HTS should also allow users to create a single class of NFTs that can each be recognized as the same type while still being individually distinct tokens.

**Comment by rahul-kothari** [comment]
At this point, it might be easier to just create an HNFTS (Hedera Non-Fungible Token Service).

**Comment by sam-at-luther** [comment]
Re: IPFS: The proposed spec discusses how this URI can point to IPFS: 
`NFTs optionally specify a URI in the token "name" attribute. This URI MAY link to data on the Hedera File Service, IPFS, a DID, AWS, or any other URI the issuer specifies.`
So it allows IPFS 👍 

Re: NFTs, I agree that standardization is necessary for the best way to do NFTs on HTS today, and possibly this may  be a separate API or service. I think it's best to break that out into a separate specification, so as to limit the scope of this spec just to the linking of asset metadata.

**Comment by cylon56** [comment]
> Re: NFTs, I agree that standardization is necessary for the best way to do NFTs on HTS today, and possibly this may be a separate API or service. I think it's best to break that out into a separate specification, so as to limit the scope of this spec just to the linking of asset metadata.

Metadata asset linking is mainly a core NFT feature so it would make sense to formally support NFTs on HTS before adopting NFT-specific features. 

I propose we create a single HIP that requests formal NFT support on Hedera with a list of critical features including asset metadata and the ability to create multiple, unique tokens of an associated type.

**Comment by sam-at-luther** [comment]
Folks are deploying NFTs today on HTS. This HIP gives them a standard way to link to token metadata.

**Comment by cylon56** [comment]
I agree that it makes sense to support metadata on HTS as it is today. I could see scenarios where someone might want to host metadata that applies to fungible tokens as well while also supporting the current NFTs being created on HTS.

The main difference between this proposal and full NFT support is that metadata links could be unique to each token created under a common type. So this proposal could target metadata JSON as a general standard and focus on defining a schema structure that can be used for both fungible tokens and NFTs. A separate proposal could then be made to create NFTs as a formal standard on HTS using the same schema proposed here.

So I propose the following:

1. Redefine this proposal to target metadata JSON as a general standard. HTS could then be the first use-case that applies to both fungible tokens and the current NFTs being created on HTS.
2. File a new proposal to formally support NFTs on Hedera as either an extension of HTS or a separate service. This would allow the creation of multiple unique tokens of the same type that also use the same metadata standard defined here.

Happy to hear feedback on this. My main goal is to ensure the standard we come with up here doesn't need to be duplicated later and that metadata JSON support on HTS isn't confused with the full NFT support that is still needed.

**Comment by rahul-kothari** [comment]
I propose a few modifications (and yes I know this will make it incompatible with ETH):
* Removing the `"images"` key to `uri` since the NFT could be for any digital asset - video, music, art etc.
* `name` and `description` will be parent key values
* Have a `custom_attributes` key to have any custom key-value pairs specific to the NFT. E.g. `"strength": 20` (useful for game related NFTs). This would be supercharged if per @cylon56, we can have several NFTs of one type.

To summarize, here is an example JSON schema:
```
{
    "title": "Asset Metadata",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "Identifies the asset to which this NFT represents"
        },
        "description": {
            "type": "string",
            "description": "Describes the asset to which this NFT represents"
        },
        "uri": {
            "type": "string",
            "description": "A URI pointing to a resource"
        },
       "custom_attributes": {
             "type": "object",
            "description": "a nested json"
       }
    }
}
```

**Sanity check:** the metadata of an actual NFT wouldn't actually have `title` or `type` and everything within `properties` would be the actual key-value pairs (instead of being nested within properties)

**Comment by sam-at-luther** [comment]
Hi @cylon56 ,

> Redefine this proposal to target metadata JSON as a general standard. HTS could then be the first use-case that applies to both fungible tokens and the current NFTs being created on HTS.

This sounds reasonable to me. I will update the proposal to indicate that it's a general way to link to token metadata on HTS, regardless of the type of token.

**Comment by sam-at-luther** [comment]
Hi @rahul-kothari , I think it's important to keep the image attribute (note that none of the properties in the schema are marked required)  that specifically has requirements around the image format, so as to facilitate the integrations with different wallets (software & hardware) and explorers that display the content. (see example in [HIP-10](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-10.md)). 

Note that in this JSON schema additional properties are allowed, so messages conforming to your example schema above would still be allowed as part of the proposal.

**Comment by sam-at-luther** [comment]
@cylon56 and @rahul-kothari , thinking about this more, since I agree that it makes sense to make this token metadata broader than just NFTs, what do you think about the following JSON schema which is an extension of the one in HIP-10, that has seen adoption already in [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155) and used heavily with the some NFT explorer? It includes `properties` which is equivalent to the proposed `custom_attributes` @rahul-kothari, and `decimals` which is relevant for fungible tokens:

```
{
    "title": "Token Metadata",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "Identifies the asset to which this token represents"
        },
        "decimals": {
            "type": "integer",
            "description": "The number of decimal places that the token amount should display"
        },
        "description": {
            "type": "string",
            "description": "Describes the asset to which this token represents"
        },
        "image": {
            "type": "string",
            "description": "A URI pointing to a resource with mime type image/* representing the asset to which this token represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive."
        },
        "properties": {
            "type": "object",
            "description": "Arbitrary properties. Values may be strings, numbers, object or arrays."
        }
    }
}
```

**Comment by cylon56** [comment]
@sam-at-luther I like this approach. It covers all our bases and leaves room for future changes in Hedera-based tokens.

**Comment by rahul-kothari** [comment]
Yea I think erc1155 like json makes so much more sense. I also agree to your previous point about keeping images for wallet integration.

**Comment by sam-at-luther** [comment]
Hi @cylon56 and @rahul-kothari . I've updated the PR above to incorporate feedback from this discussion.

**Comment by rahul-kothari** [comment]
Cool saw it. Makes sense to me. Not sure how technical HIP docs need to be/who would end up actually implementing but yea excited to see what happens next!
