### ISSUE TITLE
HIP template

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-improvement-proposal#5]
I think we should also come up with a template markdown document that they commit to a well defined folder structure. That way the repo becomes a living document of approved HIPs. Then we should create a PR template with that information.

**Comment by Cooper-Kunz** [comment]
Do you want to take a first attempt here @steven-sheehy? Otherwise I'm happy to

**Comment by steven-sheehy** [comment]
I don't think I have the bandwidth at the moment since I'm working on HCS, so feel free to. A couple examples:

[Rust RFC](https://github.com/rust-lang/rfcs/blob/master/0000-template.md)
[Kubernetes KEP](https://github.com/kubernetes/enhancements/blob/master/keps/YYYYMMDD-kep-template.md)

**Comment by Cooper-Kunz** [comment]
Sounds good, I should be able to draft something up sometime this week 

If anyone has other improvement proposal templates they like feel free to drop below for reference 👇

**Comment by kenthejr** [comment]
I like both Kubernetes & Rust proposal templates, but maybe KEP is a better fit for hashgraph.

**Comment by Cooper-Kunz** [comment]
---
hip: <to be assigned>
title: <HIP title>
author: <a list of the author's or authors' name(s) and/or username(s), or name(s) and email(s), e.g. (use with the parentheses or triangular brackets): FirstName LastName (@GitHubUsername), FirstName LastName <foo@bar.com>, FirstName (@GitHubUsername) and GitHubUsername (@GitHubUsername)>
status: Example
type: <Standard Track | Informational>
category (*only required for Standard Track): <Core | Interface | Economics | HRC>
created: <date created on, in ISO 8601 (yyyy-mm-dd) format>
requires (*optional): <HIP number(s)>
replaces (*optional): <HIP number(s)>
---

Hedera Improvement Proposal (HIP) Template

## Simple Summary
Please provide a simple summary of your improvement proposal. 

It's often beneficial to assume that those reading this are not extremely familiar with Hedera development.

## Abstract
This section is best suited for a short length technical description of the issues being addressed.

## Motivation
Please elaborate in a few sentences why this would be an improvement to the existing ecosystem of Hedera software. 

This could be a problem it solves, a use case being developed that could benefit, etc.

## Specification
The technical specification should describe the syntax and semantics of any new feature. 

This is the opportunity to let the community know how you think it should be impmlemented.

## Backwards Compatibility
HIPs that do, or could potentially introduce backwards incompatibilities must include a section outlining potential issues. 

The HIP must explain how the author proposes to deal with these incompatibilities. 

HIP submissions without a sufficient backwards compatibility treatise may be rejected outright.

## Scope and impact
Please outline all affected properties, whether clients, SDKs, or tools, that would be impacted by this change.

## Test Cases
Where makes sense, please provide outlined test cases or example test cases that would exhibit desired behavior.

## Implementation
What is the implementation plan for this issue? 

Do you already have a solution planned and waiting to be accepted? Show us here!

Does it require Hedera support, or potential funding? Let the community know.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by kenthejr** [comment]
Completed. See [hip-0000-template.md](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/hip-0000-template.md)
