### ISSUE TITLE
HTS as reference example?

### ISSUE THREAD

**Issue by ec2ainun** [hashgraph/hedera-improvement-proposal#57]
is it possible to create HIP based on Hedera Token Service (HTS)? (as complete reference example)
so that the hedera community have standard on how to create HIP in future

**Comment by kenthejr** [comment]
Does the template not meet your requirements: https://github.com/hashgraph/hedera-improvement-proposal/blob/master/hip-0000-template.md ?

There are a few additional HIPs now so it should be a bit more clear. I just want to make sure that you feel comfortable with the process now.

**Comment by ec2ainun** [comment]
@kenthejr yeah as a template, there is no final proposal yet at this moment, and i also not so sure in implementation part, whats language to use, because hedera SDK can support java, golang, and javascript

**Comment by kenthejr** [comment]
HIP-15 is probably the closest to final. Reference implementation can be in any language you want. It's a reference for other people to understand what you're trying to accomplish. Notice with hip-15 there is a JavaScript webpage and a Java library to demonstrate the feature.

**Comment by ec2ainun** [comment]
@kenthejr i see, thanks for pointing out [HIP-15][1]
i will close this issue for now, and try actively monitor discord chat and hedera service development in github

[1]: https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-15.md
