### ISSUE TITLE
Hedera Hashgraph Decentralized Identifier (DID) Method Specification

### ISSUE THREAD

**Issue by kenthejr** [hashgraph/hedera-improvement-proposal#8]
# Improvement Description

- One-line improvement description: Define Decentralized Identifier Method Specification. Recommending `did:hhg:` as the method.
- Hedera Improvement Proposal: TBD
- Primary Contact (assignee): @kenthejr

**Comment by donaldthibeau** [comment]
This is currently in the Hedera Backlog. We are looking to engage a third party to create and publish this Specification.

**Comment by cylon56** [comment]
@kenthejr Does the DID Method repo satisfy your goals for this Proposal or is there more to be done?

https://github.com/hashgraph/did-method
https://github.com/hashgraph/did-sdk-java

We've been using the DID SDK on the 3ie.io project. I'd be happy to collaborate on future improvements.

**Comment by paulmadsenhed** [comment]
Can we close this? As @cylon56 points out, the Hedera DID method exists

**Comment by kenthejr** [comment]
No HIP submitted. The W3C submission is sufficient for now.
